name: Release Branch Management

on:
  schedule:
    # Runs every Friday morning at 7 am. 
    - cron: '* 7 * * 5'
  workflow_dispatch:

jobs:
    Create_Latest_Release:
      runs-on: ubuntu-latest
      steps:
        - name: checkout-repo
          uses: actions/checkout@v4
          with:
            ref: main
            fetch-depth: 0

        - name: Get Release Dates
          run: |
            Current_Date=$(date +%u)
            sum=$((18 - Current_Date))
            echo "RELEASE_BRANCH_DATE=$(date -d "$sum days" +%Y%m%d)" >> $GITHUB_ENV
        
        - name: Create Comm Branch
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            RELEASE_BRANCH="Release-COMM-${RELEASE_BRANCH_DATE}"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -b "$RELEASE_BRANCH"
            git commit --allow-empty -m "Initial Commit for $RELEASE_BRANCH"
            git push origin "$RELEASE_BRANCH"
            gh pr create \
              --title "COMM release for ${RELEASE_BRANCH_DATE}" \
              --body "Release branch" \
              --base main \
              --head "$RELEASE_BRANCH"

        
        - name : Reset Branch
          uses: actions/checkout@v4
          with:
            ref: main
            fetch-depth: 0
          
        - name: Create Corp Branch
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            RELEASE_BRANCH="Release-CORP-${RELEASE_BRANCH_DATE}"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -b "$RELEASE_BRANCH" 
            git commit --allow-empty -m "Initial Commit for $RELEASE_BRANCH"
            git push origin "$RELEASE_BRANCH"
            gh pr create \
              --title "COMM release for ${RELEASE_BRANCH_DATE}" \
              --body "Release branch" \
              --base main \
              --head "$RELEASE_BRANCH"
              
        - name : Reset Branch 2
          uses: actions/checkout@v4
          with:
            ref: main
            fetch-depth: 0
          
        - name: Create Corp Branch
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            RELEASE_BRANCH="Release-GOV-${RELEASE_BRANCH_DATE}"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -b "$RELEASE_BRANCH"
            git commit --allow-empty -m "Initial Commit for $RELEASE_BRANCH"
            git push origin "$RELEASE_BRANCH"
            gh pr create \
              --title "COMM release for ${RELEASE_BRANCH_DATE}" \
              --body "Release branch" \
              --base main \
              --head "$RELEASE_BRANCH"
      
    Cleanup_Previous_Release:
      runs-on: ubuntu-latest
      steps:
        - name: get previous release date
          run: |
            Current_Date=`date +%u`
            sum=$((-3 - $Current_Date))
            echo 'PREV_DATE= $(date -d "$sum days" +%Y%m%d)' >>$GITHUB_ENV
        - name: Delete Branch
          run: |
            RELEASE_BRANCH= "Release-$env.PREV_DATE"
            git push origin -d $RELEASE_BRANCH
